"""Add message moderation columns

Revision ID: 3a60e76e4ede
Revises: bf251003175c
Create Date: 2025-05-29 14:10:05.844822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a60e76e4ede'
down_revision: Union[str, None] = 'bf251003175c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('original_content', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('filtered_content', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('approved_content', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('approval_status', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'approved_by')
    op.drop_column('messages', 'approval_status')
    op.drop_column('messages', 'approved_content')
    op.drop_column('messages', 'filtered_content')
    op.drop_column('messages', 'original_content')
    # ### end Alembic commands ###
